name: ghosts_on_the_train
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ptv_api_client:
    # path: '/Users/nick/git/open_source/ptv/ptv_api_client'
    git:
      url: https://github.com/nickmeinhold/ptv_api_client.git
      ref: built_value
      
  geolocator:
  flutter_redux:
  redux_remote_devtools:
  built_collection:
  built_value:
  google_maps_flutter:
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  built_value_generator:
  pedantic:
  quiver:
  test:

flutter:
  uses-material-design: true
